version: 2.1
jobs:
    common_kubernetes:
        docker:
            - image: sennerholm/google-cloud-sdk-terraform
        steps:
            - checkout
            - run: 
                name: Google Authenticate
                command: "echo ${GOOGLE_AUTH} | base64 -i --decode > /tmp/gcp-key.json ; gcloud auth activate-service-account --key-file /tmp/gcp-key.json"
            - run: 
                name: Update kubernetes
                working_directory: gce_multiple/extras/
                command: ./planverifyapply.sh common/kubernetes
    voting_redis:
        docker:
            - image: sennerholm/google-cloud-sdk-terraform
        steps:
            - checkout
            - run: 
                name: Google Authenticate
                command: "echo ${GOOGLE_AUTH} | base64 -i --decode > /tmp/gcp-key.json ; gcloud auth activate-service-account --key-file /tmp/gcp-key.json"
            - run: 
                name: Update votingService/redis
                working_directory: gce_multiple/extras/
                command: ./planverifyapply.sh votingService/redis

    voting_vote:
        docker:
            - image: sennerholm/google-cloud-sdk-terraform
        steps:
            - checkout
            - run: 
                name: Google Authenticate
                command: "echo ${GOOGLE_AUTH} | base64 -i --decode > /tmp/gcp-key.json ; gcloud auth activate-service-account --key-file /tmp/gcp-key.json"
            - run: 
                name: "Populate /root/.kube/config"
                command: "mkdir -p /root/.kube; touch /root/.kube/config"

            - run: 
                name: Update votingService/vote
                working_directory: gce_multiple/extras/
                command: ./planverifyapply.sh votingService/vote

# Orchestrate or schedule a set of jobs
workflows:
    update_google:
        jobs:
            - common_kubernetes
            - voting_redis
            - voting_vote:
                requires:
                    - common_kubernetes
                    - voting_redis
