version: 2.1
jobs:
    update_kubernetes:
        docker:
            - image: sennerholm/google-cloud-sdk-terraform
        steps:
            - checkout
            - run: 
                name: checking env
                command: env
            - run: 
                name: Check dirs
                working_directory: gce_multiple/extras/
                command: ls
            - run: 
                name: Update kubernetes
                working_directory: gce_multiple/extras/
                command: ./planverifyapply.sh common/kubernetes

# Orchestrate or schedule a set of jobs
workflows:
    update_google:
        jobs:
            - update_kubernetes
